FROM ubuntu:14.04

RUN apt-get update --fix-missing
RUN apt-get install -y apache2
RUN apt-get install -y php5 
RUN apt-get install -y libapache2-mod-php5
RUN rm /var/www/html/index.html

COPY src/index.html /var/www/html/
COPY src/run.sh /run.sh
RUN mkdir /var/www/html/js
COPY src/js/* /var/www/html/js/
RUN mkdir /var/www/html/css
COPY src/css/* /var/www/html/css/
 
RUN chmod +x /run.sh
RUN chmod 777 /var/www/html

EXPOSE 80

CMD ["/run.sh"]
